#!/bin/bash
echo "[post-rewrite hook: $1]"

changedfiles=( `git diff --no-commit-id --name-only HEAD@{1} HEAD` )

if [[ "${changedfiles[*]}" =~ "lib" ]]; then
    echo "Updating SpMP lib"
    source /opt/intel/bin/compilervars.sh intel64
    # PWD is in .git
    cd ../lib
    make clean
    make -j DBG=yes
fi
